### ISSUE TITLE
binlog-flusher repo link not working.

### ISSUE THREAD

**Issue by sjmudd** [mysql-time-machine/mysql-time-machine#7]
The link about the `binlog flusher` (just after the text _instead of this repository_) being in a new repo found here https://github.com/mysql-time-machine/mysql-time-machine/blob/master/README.md does not work.

Please can you check the link and provide the right URL for accessing the new code .

**Comment by bdevetak** [comment]
Thanks for reporting this Simon.

Broken link has been fixed now.

Bosko.
